file:
  exporter:
    csv:
      headers:
        - Firma
        - Strasse
        - Strassenzusatz
        - Ort
        - Land
        - PlZ
        - Vorname
        - Nachname
        - Kunden-ID
      fieldNames:
        - firmenname
        - strasse
        - strassenzusatz
        - ort
        - land
        - plz
        - vorname
        - nachname
        - kundenId

      outputPath: D:/Development/Output
      inputPath: D:/Development/Output

csv:
  server:
    url: https://s3-eu-central-2.ionoscloud.com/dw-2022-11-28-file-exporter-demo/demo/ajbn2022-113334444-Test.csv

